export const currentUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: null,
  isPro: true,
};

export const itemTypes = [
  { id: "type_snippet", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_file", name: "file", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "image", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type_link", name: "link", icon: "Link", color: "#10b981", isSystem: true },
];

export const itemTypeCounts: Record<string, number> = {
  snippet: 24,
  prompt: 18,
  command: 15,
  note: 12,
  file: 5,
  image: 3,
  link: 8,
};

export const collections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    createdAt: "2025-01-02T00:00:00Z",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    createdAt: "2025-01-03T00:00:00Z",
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    createdAt: "2025-01-04T00:00:00Z",
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    createdAt: "2025-01-05T00:00:00Z",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    createdAt: "2025-01-06T00:00:00Z",
  },
];

export const items = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "TEXT" as const,
    content: "export function useAuth() {\n  const session = useSession();\n  return session;\n}",
    description: "Custom authentication hook for React applications",
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    itemTypeId: "type_snippet",
    tags: ["react", "auth", "hooks"],
    collectionIds: ["col_1"],
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-01-15T00:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "TEXT" as const,
    content: "async function fetchWithRetry(url: string, retries = 3) {\n  // Fetch wrapper with exponential backoff retry logic\n}",
    description: "Fetch wrapper with exponential backoff retry logic",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    itemTypeId: "type_snippet",
    tags: ["api", "error-handling"],
    collectionIds: ["col_1"],
    createdAt: "2025-01-12T00:00:00Z",
    updatedAt: "2025-01-12T00:00:00Z",
  },
  {
    id: "item_3",
    title: "Code review prompt",
    contentType: "TEXT" as const,
    content: "Review this code for bugs, performance issues, and best practices. Provide specific suggestions.",
    description: "General code review prompt",
    language: null,
    isFavorite: true,
    isPinned: false,
    itemTypeId: "type_prompt",
    tags: ["code-review", "ai"],
    collectionIds: ["col_6"],
    createdAt: "2025-01-10T00:00:00Z",
    updatedAt: "2025-01-10T00:00:00Z",
  },
  {
    id: "item_4",
    title: "git reset --hard HEAD~1",
    contentType: "TEXT" as const,
    content: "git reset --hard HEAD~1",
    description: "Undo the last commit and discard changes",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_command",
    tags: ["git", "reset"],
    collectionIds: ["col_5"],
    createdAt: "2025-01-08T00:00:00Z",
    updatedAt: "2025-01-08T00:00:00Z",
  },
  {
    id: "item_5",
    title: "Python list comprehension patterns",
    contentType: "TEXT" as const,
    content: "# Filter and transform\nresult = [f(x) for x in iterable if condition(x)]",
    description: "Common Python list comprehension patterns",
    language: "python",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_snippet",
    tags: ["python", "list-comprehension"],
    collectionIds: ["col_2"],
    createdAt: "2025-01-06T00:00:00Z",
    updatedAt: "2025-01-06T00:00:00Z",
  },
  {
    id: "item_6",
    title: "DevNest project context",
    contentType: "TEXT" as const,
    content: "DevNest is a unified hub for developer knowledge & resources...",
    description: "Main project context file for AI assistants",
    language: null,
    isFavorite: true,
    isPinned: false,
    itemTypeId: "type_file",
    tags: ["context", "ai"],
    collectionIds: ["col_3"],
    createdAt: "2025-01-04T00:00:00Z",
    updatedAt: "2025-01-04T00:00:00Z",
  },
];
